config/routes.rb
Rails.application.routes.draw do
  get 'outputs/new'
  devise_for :users
  root to:"books#index"
  resources :books do
    resources :preparations
    resources :outputs, only:[ :new, :create, :edit, :update, :detroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/book.rb
class Book < ApplicationRecord
  validates :book_title, presence: true
  validates :author, presence: true
  validates :total_page, presence: true

  belongs_to :user
  has_one :preparation,dependent: :destroy
  has_one :output,dependent: :destroy
  has_one_attached :image
end

app/models/output.rb
class Output < ApplicationRecord
  belongs_to :book
end

app/models/preparation.rb
class Preparation < ApplicationRecord
  validates :reason, presence: true
  validates :get_ability, presence: true
  validates :status, presence: true
  validates :prior_knowledge, presence: true
  validates :unknown, presence: true
  validates :book_id, presence: true

  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, presence: true, length: { maximum: 10 }
  has_many :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  
  
  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys: [:nickname])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_gate, except: [:index,:new,:create,:detroy]
  def index
    @book = Book.includes(:user).order("created_at DESC")
  end

  def new
    @book=Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_path
    else
      render :new
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    if @book.update(book_params)
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def show
    @book= Book.find(params[:id])
    if Preparation.exists?(book_id:@book.id)
      @preparation=Preparation.find_by(book_id:@book.id)
    end
    if Output.exists?(book_id:@book.id)
      @output=Output.find_by(book_id:@book.id)
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  
  private
  def book_params
    params.require(:book).permit(:book_title, :author, :total_page, :image).merge(user_id: current_user.id)
  end

  def set_gate
    @book = Book.find(params[:id])
    redirect_to books_path if current_user.id != @book.user_id 
  end
end

app/controllers/outputs_controller.rb
class OutputsController < ApplicationController
  before_action :authenticate_user!
  def new
    @book=Book.find(params[:book_id])
    @output=Output.new
  end
  def create
    @book=Book.find(params[:book_id])
    @output=Output.new(output_params)
    if @output.save
      redirect_to book_path(@book.id)
    else
      render :new
    end
  end
  def edit
    @book=Book.find(params[:book_id])
    @output=Output.find_by(book_id:@book.id)
  end
  
  def update
    @book=Book.find(params[:book_id])
    @output=Output.find(params[:id])
    if @output.update(output_params)
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end
  

  private
  def output_params
    params.require(:output).permit(:text).merge(book_id:params[:book_id])
  end
end

app/controllers/preparations_controller.rb
class PreparationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @book= Book.find(params[:book_id])
    @preparation=Preparation.find_by(book_id:@book.id)
  end

  def new
    @book=Book.find(params[:book_id])
    @preparation=Preparation.new
  end

  def create
    @preparation=Preparation.new (preparation_params)
    if @preparation.save
      redirect_to book_path(@preparation.book_id)
    else
      render :new
    end
  end

  def edit
     @book = Book.find(params[:book_id])
     @preparation=Preparation.find_by(book_id:@book.id)
   end

  def update
    @book= Book.find(params[:book_id])
    @preparation=Preparation.find (params[:id])
    if @preparation.update(preparation_params)
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  private
  def preparation_params
    params.require(:preparation).permit(:reason, :get_ability, :status, :prior_knowledge,:unknown).merge(book_id:params[:book_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/outputs_helper.rb
module OutputsHelper
end

app/helpers/preparations_helper.rb
module PreparationsHelper
end

app/views/books/edit.html.erb
<%= render "shared/header" %>

<div class='book-add-main'>

  <div class="book-add">
    <%= form_with model: @book, url:book_path(@book.id),local: true do |f| %>
    <h3 class='book-new'>本の内容を入力</h3>
    <p class='book-add-title'> 本のタイトル</p>
    <div class='book-add-title'>
    <%= f.text_area :book_title, class:"book-new-form", id:"book-title", placeholder:"本のタイトルを入力" %>
    </div>
    <p class='book-add-title'>本の著者</p>
    <div class='book-add-title'>
    <%= f.text_area :author, class:"book-new-form", id:"book-author", placeholder:"本の著者を入力" %>
    </div>
    <p class='book-add-title'>本の総ページ数</p>
    <div class='book-add-title'>
    <%= f.text_area :total_page,class:"book-new-form", id:"book-page", placeholder:"本の総ページを入力" %>
    </div>
    <p class='book-add-title'>本の画像</p>
    <div class='book-add-image'>
    <%= f.file_field :image, id:"book-add-image" %>
    </div> 
    <div class='submit'>
    <%= f.submit "登録する" ,class:"sell-btn" %> 
    </div>
    <div class='book-link-back'>
    <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <% end %>
  </div>
<div>

app/views/books/index.html.erb
<!DOCTYPE HTML>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <link href='http://fonts.googleapis.com/css?family=Paytone+One' rel='stylesheet' type='text/css'>
    <link href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" rel='stylesheet'>
    <link rel="stylesheet" href="style.scss">
    

    <title>re3-book</title>
  </head>
  <body>
   <%= render "shared/header" %>
    
    <div class = "box4">
      <div class = "bottom">
        <img src="assets/books/retop.jpg" alt="" class ="backimg" >
        <div class="slider">
          <ul class="slides">
            <%num=0%>
              <% @book.each do |book|%>
                <div id=slide-<%num%>>
                  <%= link_to book_path(book.id) ,class:'booklink' do %>
                    <li class='list'>
                      <div class='book-image'>
                        <%= image_tag book.image, :size =>'240x360', class: "book-img" if book.image.attached? %>
                      </div>
                      <p class='book-top-title'>本のタイトル：<%= book.book_title %></p>
                      <p class='book-top-author'>著者：<%= book.author %></p>
                      <span class='book-top-page'><%= book.total_page %>ページ</span>
                    </li>
                  <% end %>
                  <%num=num+1%>
                </div>
              <% end %> 
            </ul>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/books/new.html.erb
<%= render "shared/header" %>

<div class='book-add-main'>

  <div class="book-add">
    <%= form_with model: @book, local: true do |f| %>
    <h3 class='book-new'>本の内容を入力</h3>
    <p class='book-add-title'> 本のタイトル</p>
    <div class='book-add-title'>
    <%= f.text_area :book_title, class:"book-new-form", id:"book-title", placeholder:"本のタイトルを入力" %>
    </div>
    <p class='book-add-title'>本の著者</p>
    <div class='book-add-title'>
    <%= f.text_area :author, class:"book-new-form", id:"book-author", placeholder:"本の著者を入力" %>
    </div>
    <p class='book-add-title'>本の総ページ数</p>
    <div class='book-add-title'>
    <%= f.text_area :total_page,class:"book-new-form", id:"book-page", placeholder:"本の総ページを入力" %>
    </div>
    <p class='book-add-title'>本の画像</p>
    <div class='book-add-image'>
    <%= f.file_field :image, id:"book-add-image" %>
    </div> 
    <div class='submit'>
    <%= f.submit "登録する" ,class:"sell-btn" %> 
    </div>
    <div class='book-link-back'>
    <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <% end %>
  </div>
<div>

app/views/books/show.html.erb
<!DOCTYPE HTML>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <link href='http://fonts.googleapis.com/css?family=Paytone+One' rel='stylesheet' type='text/css'>
    <link href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" rel='stylesheet'>
    <link rel="stylesheet" href="style.scss">
    

    <title>re3-book</title>
  </head>
  <body>
  <%= render "shared/header" %>
  <div class="box5">
    <div class="boxB">
      <div class="d_button"> 
        <button><%= link_to '本を消去する',book_path(@book.id), method: :delete %></button>
      </div>
      <div class="box6">
        <div class="leftcontent">
          <div class="image">
            <%= image_tag @book.image.variant(resize: '350x500'), class: "book-img" %>
          </div>
          <%if Preparation.exists?(book_id:@book.id)%>
              <ul>
                <div class="title1">
                  <li>ーーメンタルマップーー</li>
                </div>
                <li>・なぜこの本を読もうと思ったのか？</li> 
                <div class="comment"><%=@preparation.reason%></div>
                <li>・この本から何を得たいのか？</li>
                <div class="comment"><%=@preparation.get_ability%></div>
                <li>・読んだ後、どのような状態になりたいと願っているのか？</li>
                <div class="comment"><%=@preparation.status%></div>
                <div class="title1">
                  <li>ーーギュリオシティーギャップーー</li>
                </div>
                <li>・自分があらかじめ持っている知識</li> 
                <div class="comment"><%=@preparation.prior_knowledge%></div>
                <li>・本の中に書かれた自分が知らない知識</li> 
                <div class="comment"><%=@preparation.unknown%></div>
              </ul>
          <%else%>
            <div class='preparation-list'>
              <ul>
                <div class="title1">
                  <li>ーー読む前の準備ーー</li>
                </div>
                <li>・メンタルマップ'</li>
                <li>・キュリオシティギャップ</li>
              </ul>
            </div>
          <%end%>
        </div>
        <div class="button">
          <%if Preparation.exists?(book_id:@book.id)%>
            <button><%= link_to '編集',edit_book_preparation_path(@book.id,@preparation.id) %></button>
          <%else%>
            <button><%= link_to '編集',new_book_preparation_path(@book.id) %></button>
          <%end%>
        </div>
      </div>
      <div class="box7">
        <%if Output.exists?(book_id:@book.id)%>
          <h1 class=title1>要約</h1>
          <p><%=@output.text%></p>
          <div class="button">
            <button><%= link_to '編集',edit_book_output_path(book_id:@book.id) %></button>
          </div>
        <%else%>
          <div class="button">
            <button><%= link_to '要約の記入',new_book_output_path(book_id:@book.id) %></button>
          </div>
        <%end%>
      </div>
    </div>
  </div>



</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rebook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/outputs/edit.html.erb
<%= render "shared/header" %>

<div class='book-wrapup'>
    <div class='text-box'>
      <%= form_with model: @output, url:book_output_path(@book.id,@output.id),local: true do |f| %>
        <div class='out-text'>本の要約を入力</div>
        <div class='output-box'>
          <%= f.text_area :text, class:"output-form", placeholder:"本の要約を入力",size: "110x25" %>
        </div>
        <div class='btn'>
         <%= f.submit "登録する" ,class:"sell-btn" %> 
        </div>
        <div class='link-back'>
         <%=link_to '戻る',book_path(@book.id)%>
        </div>
      <% end %>
    </div>
</div>

app/views/outputs/new.html.erb
<%= render "shared/header" %>

<div class='book-wrapup'>
    <div class='text-box'>
      <%= form_with model: @output, url:book_outputs_path(@book.id),local: true do |f| %>
        <div class='out-text'>本の要約を入力</div>
        <div class='output-box'>
          <%= f.text_area :text, class:"output-form", placeholder:"本の要約を入力",size: "110x25" %>
        </div>
        <div class='btn'>
         <%= f.submit "登録する" ,class:"sell-btn" %> 
        </div>
        <div class='link-back'>
         <%=link_to '戻る',book_path(@book.id)%>
        </div>
      <% end %>
    </div>
</div>

app/views/preparations/edit.html.erb
<%= render "shared/header" %>
<div class='preparations-background'>
  <div class='preparations'>
    <%= form_with model: @preparation, url: book_preparation_path(@book.id), local: true do |f| %>
     <div class='preparation'>
      <b class='new-preparation-title'>メンタルマップ</b>
      <div class='new-preparation'>なぜこの本を読もうと思ったのか？</div> 
      <div class='new-preparation-from'>
        <%=f.text_area :reason,class:"preparation-from", placeholder:"例：1ヶ月に体重を１キロずつ落としたい"%>
      </div>
      <div class='new-preparation'>この本から何を得たいのか？</div>
      <div class='new-preparation-from'>
        <%=f.text_area :get_ability,class:"preparation-from", placeholder:"例：異動先の若手と良好な関係を築くためのノウハウが知りたい"%>
      </div>
      <div class='new-preparation'>読んだ後、どのような状態になりたいと願っているのか？</div>
      <div class='new-preparation-from'>
        <%=f.text_area :status,class:"preparation-from", placeholder:"例：ストレスをコントロールする方法を学び、しんどい状況を改善させてい"%>
      </div>
      <b class='new-preparation-title'>ギュリオシティーギャップ</b>
      <div class='new-preparation'>自分があらかじめ持っている知識</div> 
      <div class='new-preparation-from'>
        <%=f.text_area :prior_knowledge,class:"preparation-from", placeholder:"例：ストーリーテリングについて"%>
      </div>
      <div class='new-preparation'>本の中に書かれた自分が知らない知識</div> 
      <div class='new-preparation-from'>
        <%=f.text_area :unknown,class:"preparation-from", placeholder:"例：マインドフルスピーキングとは？"%>
      </div>
  
      <div class='btn'>
        <%= f.submit "登録する" ,class:"sell-btn" %> 
      </div>
      <div class='link-back'>
        <%=link_to 'もどる', book_path(@book.id), class:"back-btn" %>
      </div>
    
    <%end%>
  </div>
</div>

app/views/preparations/index.html.erb
<%= render "shared/header" %>
<div class='unknown'>
  <div class='book-info'>
    <div class='book-image'>
      <%= image_tag @book.image.variant(resize: '350x500'), class: "book-img" %>
    </div>
    <h3 class='book-title'>
      <%= @book.book_title %>
    </h3>
    <div class='author'>
      <%= @book.author %>
    </div>
    <div class='level-of-achievement'>
      <%= @book.total_page %>
    </div>
  </div>
  
  <div class='book-preparation'>
    <div class='reason'>
      <%= @preparation.reason %>
    </div>
    <div class='get-ability'>
      <%= @preparation.get_ability %>
    </div>
    <div class='status'>
      <%= @preparation.status %>
    </div>
    <div class='prior-knowledge'>
      <%= @preparation.prior_knowledge %>
    </div>
    <div class='unknown'>
      <%= @preparation.unknown %>
    </div>
  </div>
</div>

app/views/preparations/new.html.erb
<%= render "shared/header" %>
<div class='preparations-background'>
  <div class='preparations'>
    <%= form_with model: @preparation, url: book_preparations_path(@book.id), local: true do |f| %>
     <div class='preparation'>
      <b class='new-preparation-title'>メンタルマップ</b>
      <div class='new-preparation'>なぜこの本を読もうと思ったのか？</div> 
      <div class='new-preparation-from'>
        <%=f.text_area :reason,class:"preparation-from", placeholder:"例：1ヶ月に体重を１キロずつ落としたい"%>
      </div>
      <div class='new-preparation'>この本から何を得たいのか？</div>
      <div class='new-preparation-from'>
        <%=f.text_area :get_ability,class:"preparation-from", placeholder:"例：異動先の若手と良好な関係を築くためのノウハウが知りたい"%>
      </div>
      <div class='new-preparation'>読んだ後、どのような状態になりたいと願っているのか？</div>
      <div class='new-preparation-from'>
        <%=f.text_area :status,class:"preparation-from", placeholder:"例：ストレスをコントロールする方法を学び、しんどい状況を改善させてい"%>
      </div>
      <b class='new-preparation-title'>ギュリオシティーギャップ</b>
      <div class='new-preparation'>自分があらかじめ持っている知識</div> 
      <div class='new-preparation-from'>
        <%=f.text_area :prior_knowledge,class:"preparation-from", placeholder:"例：ストーリーテリングについて"%>
      </div>
      <div class='new-preparation'>本の中に書かれた自分が知らない知識</div> 
      <div class='new-preparation-from'>
        <%=f.text_area :unknown,class:"preparation-from", placeholder:"例：マインドフルスピーキングとは？"%>
      </div>
  
      <div class='btn'>
        <%= f.submit "登録する" ,class:"sell-btn" %> 
      </div>
      <div class='link-back'>
        <%=link_to 'もどる', book_path(@book.id), class:"back-btn" %>
      </div>
    
    <%end%>
  </div>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
   <div class = "boxA">
      <div class="box1">
        <div class="site">
           <h1>
            <%= link_to books_path do%>
              <img src="/assets/books/titlelogo.png" alt="re3-book" width="250" height="40">
            <%end%>
          </h1>
        </div>
      </div>
      <div class = "box2">
        <div class="login-info">
           <ul>
            <% if user_signed_in? %>
              <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
              <li class="user-nickname"><%= current_user.nickname%></li>
            <% else %>
              <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
              <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class = "box3">
      <nav class = "menu">
        <ul>
          <li><%= link_to '書籍登録',new_book_path, class: 'book-btn'  %></li>
          <li><a href="#">瞑想</a></li>
        </ul>
      </nav>
    </div>

</header>